### ISSUE TITLE
Import issue: concurrency

### ISSUE THREAD

**Issue by shivareddyiirs** [addypy/datagovindia#2] opened 2021-06-17 10:01 UTC
>>DataGovIndia("API-KEY")

Step (1/2) : API key is VALID                                             
	You don't need to enter it again                          
Traceback (most recent call last):PI meta-data. This may take a few seconds........               
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/datagovindia/__init__.py", line 531, in __init__
    self.assets       = util.git_assets()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/datagovindia/util.py", line 91, in __init__
    asset_data = fetch_assets_from_github(asset_url_seq)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/datagovindia/util.py", line 17, in fetch_assets_from_github
    with concurrent.futures.ThreadPoolExecutor() as executor: 
AttributeError: module 'concurrent' has no attribute 'futures'

Python version is 3.9.4
OS: MacOS

**Comment by addypy** [comment] 2021-06-17 11:18
@shivareddyiirs  I wasn't able to reproduce the issue. The datagovindia package uses the `concurrent.futures` module which is a Python standard library (included with Python) to download resources from this repo. 

I suspect a problem with your current Python build.

I would suggest the following - 

1. Re-install `futures` -- ` pip install -U futures` 
(`futures` has been included in the concurrent module Python 3.2 and later. and doesn't need to be installed separately. But since there may be a build error, you should try reinstalling futures.)

2.  If this doesn't work, try one of these - reinstalling your current version of Python/ upgrading to Python 3.9.5? 

Also, could please copy the following, and show us the output? 
```python
import concurrent 
print(dir(concurrent))
```

**Comment by shivareddyiirs** [comment] 2021-06-18 06:00
I have installed and upgraded futures library but still facing same issue. Output after running above code is as below:

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

**Comment by shivareddyiirs** [comment] 2021-06-18 06:26
I even tried installing python 3.8.10. here also facing same issue.

**Comment by addypy** [comment] 2021-06-18 06:55
@shivareddyiirs  Strange. Ordinarily, 'futures' would be available in the output you posted. 

I would request you to try this and share the output.

```python
import concurrent.futures
print(dir(concurrent))
```

If importing it this way correctly imports the 'futures' package, then a change in our package would be warranted.

**Comment by addypy** [comment] 2021-06-22 14:36
@shivareddyiirs have updated the package with some improvements and a more explicit futures import. 
Please update the library with pip -

`pip install -U datagovindia`

Closing this issue.

**Closed as completed** 2021-06-25 05:54 UTC
